# Generated by Django 5.0.2 on 2024-03-01 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='short_description',
        ),
    ]
