# Generated by Django 5.0.2 on 2024-03-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_brand_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ai_bot_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
