# Generated by Django 5.0.2 on 2024-03-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_order_shippingprice_observation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='modification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
